// Code generated by 'go build ./cmd/tools' - DO NOT EDIT.
// This file tracks development tools and dependencies.
// See: https://github.com/golang/go/wiki/Modules#how-to-track-tool-dependencies

//go:build tools
// +build tools

package main

import (
	// govulncheck scans Go code for known vulnerabilities in dependencies.
	// Essential for security auditing and compliance.
	// See: https://pkg.go.dev/golang.org/x/vuln/cmd/govulncheck
	_ "golang.org/x/vuln/cmd/govulncheck"
)
