// Code generated by 'go build ./cmd/tools' - DO NOT EDIT.
// This file tracks development tools and dependencies.
// See: https://github.com/golang/go/wiki/Modules#how-to-track-tool-dependencies

//go:build tools
// +build tools

package main

import (
	// golangci-lint is a fast linter aggregator written in Go.
	// Used for code quality checks across the project.
	// See: https://golangci-lint.run
	_ "github.com/golangci/golangci-lint/cmd/golangci-lint"

	// govulncheck scans Go code for known vulnerabilities in dependencies.
	// Essential for security auditing and compliance.
	// See: https://pkg.go.dev/golang.org/x/vuln/cmd/govulncheck
	_ "golang.org/x/vuln/cmd/govulncheck"
)
