package tui

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/charmbracelet/huh"
	"github.com/charmbracelet/lipgloss"
)

// CredentialConfig holds the credential configuration
type CredentialConfig struct {
	CredentialsPath string
	ProjectID       string
	SaveToEnv       bool
	ShellType       string
}

// RunSetupWizard runs the interactive setup wizard
func RunSetupWizard() (*CredentialConfig, error) {
	config := &CredentialConfig{}

	// Welcome message
	welcomeStyle := lipgloss.NewStyle().
		Bold(true).
		Foreground(lipgloss.Color("#FF6B6B")).
		Border(lipgloss.RoundedBorder()).
		BorderForeground(lipgloss.Color("#6C5CE7")).
		Padding(1, 2).
		Margin(1, 0)

	welcome := welcomeStyle.Render("🚀 GA4 Manager Setup Wizard\n\nLet's configure your Google Cloud credentials!")
	fmt.Println(welcome)

	// Create the form
	form := huh.NewForm(
		// Group 1: Google Cloud Credentials
		huh.NewGroup(
			huh.NewInput().
				Title("Google Cloud Credentials Path").
				Description("Path to your service account JSON file").
				Placeholder("/path/to/credentials.json").
				Value(&config.CredentialsPath).
				Validate(validateCredentialsPath),

			huh.NewInput().
				Title("Google Cloud Project ID").
				Description("Your GCP project ID (optional but recommended)").
				Placeholder("your-gcp-project-id").
				Value(&config.ProjectID),
		),

		// Group 2: Save Configuration
		huh.NewGroup(
			huh.NewConfirm().
				Title("Save to .env file?").
				Description("Create/update .env file in the current directory").
				Value(&config.SaveToEnv),

			huh.NewSelect[string]().
				Title("Shell Type (for export instructions)").
				Description("Select your shell to get the right export commands").
				Options(
					huh.NewOption("Bash (~/.bashrc)", "bash"),
					huh.NewOption("Zsh (~/.zshrc)", "zsh"),
					huh.NewOption("Fish (~/.config/fish/config.fish)", "fish"),
				).
				Value(&config.ShellType),
		),
	)

	// Run the form
	err := form.Run()
	if err != nil {
		return nil, err
	}

	return config, nil
}

// validateCredentialsPath validates that the credentials file exists
func validateCredentialsPath(path string) error {
	if path == "" {
		return fmt.Errorf("credentials path cannot be empty")
	}

	// Expand ~ to home directory
	if path[0] == '~' {
		homeDir, err := os.UserHomeDir()
		if err != nil {
			return fmt.Errorf("could not expand home directory: %w", err)
		}
		path = filepath.Join(homeDir, path[1:])
	}

	// Check if file exists
	if _, err := os.Stat(path); os.IsNotExist(err) {
		return fmt.Errorf("file does not exist: %s", path)
	}

	// Check if it's a JSON file
	if filepath.Ext(path) != ".json" {
		return fmt.Errorf("credentials file must be a .json file")
	}

	return nil
}

// SaveToEnvFile saves the configuration to .env file
func SaveToEnvFile(config *CredentialConfig) error {
	// Expand ~ if present
	credPath := config.CredentialsPath
	if credPath[0] == '~' {
		homeDir, err := os.UserHomeDir()
		if err != nil {
			return fmt.Errorf("could not expand home directory: %w", err)
		}
		credPath = filepath.Join(homeDir, credPath[1:])
	}

	// Get absolute path
	absPath, err := filepath.Abs(credPath)
	if err != nil {
		return fmt.Errorf("could not get absolute path: %w", err)
	}

	// Create .env content
	envContent := fmt.Sprintf(`# GA4 Manager Configuration
# Generated by: ga4 init

# Google Cloud Credentials
GOOGLE_APPLICATION_CREDENTIALS=%s

# Google Cloud Project ID
GOOGLE_CLOUD_PROJECT=%s
`, absPath, config.ProjectID)

	// Write to .env file
	err = os.WriteFile(".env", []byte(envContent), 0644)
	if err != nil {
		return fmt.Errorf("could not write .env file: %w", err)
	}

	return nil
}

// PrintShellInstructions prints shell-specific export instructions
func PrintShellInstructions(config *CredentialConfig) {
	// Expand ~ if present
	credPath := config.CredentialsPath
	if credPath[0] == '~' {
		homeDir, _ := os.UserHomeDir()
		credPath = filepath.Join(homeDir, credPath[1:])
	}

	// Get absolute path
	absPath, _ := filepath.Abs(credPath)

	headerStyle := lipgloss.NewStyle().
		Bold(true).
		Foreground(lipgloss.Color("#4ECDC4")).
		Margin(1, 0)

	codeStyle := lipgloss.NewStyle().
		Foreground(lipgloss.Color("#FFE66D")).
		Padding(0, 2)

	tipStyle := lipgloss.NewStyle().
		Foreground(lipgloss.Color("#95A3A4")).
		Italic(true)

	fmt.Println(headerStyle.Render("\n📝 Shell Configuration"))

	switch config.ShellType {
	case "bash":
		fmt.Println(tipStyle.Render("Add these lines to ~/.bashrc or ~/.bash_profile:"))
		fmt.Println(codeStyle.Render(fmt.Sprintf(`
export GOOGLE_APPLICATION_CREDENTIALS="%s"
export GOOGLE_CLOUD_PROJECT="%s"
`, absPath, config.ProjectID)))
		fmt.Println(tipStyle.Render("Then run: source ~/.bashrc"))

	case "zsh":
		fmt.Println(tipStyle.Render("Add these lines to ~/.zshrc:"))
		fmt.Println(codeStyle.Render(fmt.Sprintf(`
export GOOGLE_APPLICATION_CREDENTIALS="%s"
export GOOGLE_CLOUD_PROJECT="%s"
`, absPath, config.ProjectID)))
		fmt.Println(tipStyle.Render("Then run: source ~/.zshrc"))

	case "fish":
		fmt.Println(tipStyle.Render("Add these lines to ~/.config/fish/config.fish:"))
		fmt.Println(codeStyle.Render(fmt.Sprintf(`
set -gx GOOGLE_APPLICATION_CREDENTIALS %s
set -gx GOOGLE_CLOUD_PROJECT %s
`, absPath, config.ProjectID)))
		fmt.Println(tipStyle.Render("Then run: source ~/.config/fish/config.fish"))
	}

	fmt.Println(headerStyle.Render("\n✅ Next Steps"))
	fmt.Println("  1. Add the environment variables to your shell config (see above)")
	fmt.Println("  2. Source your shell config or restart your terminal")
	fmt.Println("  3. Run: ga4 validate --all")
	fmt.Println("  4. Start using: ga4")
}
